# Generated by Django 3.1.7 on 2021-03-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='created on')),
                ('updated_on', models.DateField(auto_now=True, verbose_name='updated on')),
                ('q1', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], null=True, verbose_name='question 1')),
                ('q2', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], null=True, verbose_name='question 2')),
                ('q3', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], null=True, verbose_name='question 3')),
                ('q4', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], null=True, verbose_name='question 4')),
                ('q5', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], null=True, verbose_name='question 5')),
                ('examination_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.examinationsession')),
            ],
        ),
    ]
